# Generated by Django 5.2.11 on 2026-03-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="weekly_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="core.weeklymodule",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="weekly_module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="core.weeklymodule",
            ),
        ),
    ]
