# Generated by Django 5.2.11 on 2026-03-01 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_calendarevent_activity_and_unique_constraints"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="todoitem",
            unique_together={("user", "activity")},
        ),
        migrations.AddField(
            model_name="todoitem",
            name="quiz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.quiz",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="todoitem",
            unique_together={("user", "activity"), ("user", "quiz")},
        ),
    ]
