# Generated by Django 5.2.11 on 2026-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_todoitem_unique_together_todoitem_quiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="preview_file_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
