# Generated by Django 5.2.12 on 2026-03-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_coursefile_preview_file_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="personal_email",
            field=models.EmailField(
                blank=True,
                help_text="Personal email for sending login credentials",
                max_length=254,
                null=True,
            ),
        ),
    ]
