# Generated by Django 5.2.12 on 2026-03-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_requires_setup_passwordresetrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submission",
            options={"ordering": ["-attempt_number"]},
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="activity",
            name="attempt_limit",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="activity",
            name="score_selection_policy",
            field=models.CharField(
                choices=[("latest", "Latest"), ("highest", "Highest")],
                default="highest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="score_selection_policy",
            field=models.CharField(
                choices=[("latest", "Latest"), ("highest", "Highest")],
                default="highest",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("activity", "student", "attempt_number")},
        ),
    ]
