# Generated by Django 5.2.12 on 2026-03-15 04:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_activitycomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSectionGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this course group",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description", null=True
                    ),
                ),
                (
                    "school_year",
                    models.CharField(
                        help_text="Academic year (e.g., '2024-2025')", max_length=20
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        blank=True,
                        help_text="Semester (optional)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_sections",
                    models.ManyToManyField(
                        help_text="Select up to 10 course sections to include in this group",
                        limit_choices_to={"is_active": True},
                        related_name="course_groups",
                        to="core.coursesection",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
