# Generated by Django 5.2.12 on 2026-03-21 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_course_section_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Subject", "verbose_name_plural": "Subjects"},
        ),
        migrations.AlterModelOptions(
            name="coursesection",
            options={
                "verbose_name": "Class Offering",
                "verbose_name_plural": "Class Offerings",
            },
        ),
        migrations.AlterModelOptions(
            name="coursesectiongroup",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Enrollment Group",
                "verbose_name_plural": "Enrollment Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "verbose_name": "Class Section",
                "verbose_name_plural": "Class Sections",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(
                help_text="Unique identifier code (e.g., 'CP102', 'MATH101')",
                max_length=50,
                verbose_name="Course Code",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Full name of the course (e.g., 'Introduction to Programming')",
                max_length=255,
                verbose_name="Course Title",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="course",
            field=models.ForeignKey(
                help_text="Select the subject to be taught",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_sections",
                to="core.course",
                verbose_name="Subject",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="section",
            field=models.ForeignKey(
                help_text="Select the class section that will take this subject",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_sections",
                to="core.section",
                verbose_name="Class Section",
            ),
        ),
        migrations.AlterField(
            model_name="coursesection",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Assign a teacher to teach this subject to this class section",
                limit_choices_to={"role": "teacher"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_course_sections",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Teacher",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course_section",
            field=models.ForeignKey(
                help_text="Select the class offering to enroll the student in",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="core.coursesection",
                verbose_name="Class Offering",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Select a student to enroll",
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Grade 7", "Grade 7"),
                    ("Grade 8", "Grade 8"),
                    ("Grade 9", "Grade 9"),
                    ("Grade 10", "Grade 10"),
                    ("Grade 11", "Grade 11"),
                    ("Grade 12", "Grade 12"),
                ],
                help_text="The grade level this section belongs to",
                max_length=20,
                verbose_name="Grade Level",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                help_text="The class section identifier (e.g., 'ICT-A', 'STEM-B1')",
                max_length=100,
                verbose_name="Section Name",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="school_year",
            field=models.CharField(
                help_text="Academic year (e.g., '2024-2025')",
                max_length=20,
                verbose_name="School Year",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="strand",
            field=models.CharField(
                choices=[
                    ("STEM", "STEM"),
                    ("ABM", "ABM"),
                    ("HUMSS", "HUMSS"),
                    ("TVL", "TVL"),
                    ("GAS", "GAS"),
                    ("NONE", "NONE"),
                ],
                default="NONE",
                help_text="Academic strand for senior high school (e.g., ICT, STEM, ABM)",
                max_length=10,
                verbose_name="Strand/Track",
            ),
        ),
        migrations.CreateModel(
            name="IDCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(help_text="Year for this counter (e.g., 2024)"),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[("student", "Student"), ("teacher", "Teacher")],
                        help_text="Type of ID: student or teacher",
                        max_length=10,
                    ),
                ),
                (
                    "prefix",
                    models.IntegerField(
                        default=1,
                        help_text="Prefix for ID (starts at 1, increments when sequential overflows 9999)",
                    ),
                ),
                (
                    "sequential",
                    models.IntegerField(
                        default=0, help_text="Sequential number (1-9999)"
                    ),
                ),
            ],
            options={
                "verbose_name": "ID Counter",
                "verbose_name_plural": "ID Counters",
                "unique_together": {("year", "id_type")},
            },
        ),
    ]
