# Generated by Django 5.2.12 on 2026-03-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_id_counter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "ordering": [
                    "meeting__date",
                    "student__last_name",
                    "student__first_name",
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Account", "verbose_name_plural": "Accounts"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                help_text="Middle name or initial (optional)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="First name (e.g., 'Juan')", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                help_text="Last name / Surname (e.g., 'Dela Cruz')", max_length=100
            ),
        ),
    ]
