# Generated by Django 5.2.12 on 2026-03-22 09:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_teacher_advisory_irregular_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_irregular",
            field=models.BooleanField(
                default=False,
                help_text="Mark this student as irregular — can be enrolled across sections by their advisory teacher",
            ),
        ),
        migrations.AlterField(
            model_name="teacheradvisory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
