# Generated by Django 5.2.12 on 2026-03-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0019_user_is_irregular_alter_teacheradvisory_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idcounter",
            name="id_type",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                help_text="Student or Teacher ID type",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="idcounter",
            name="prefix",
            field=models.IntegerField(
                default=1, help_text="Prefix number (1, 2, 3... for overflow handling)"
            ),
        ),
        migrations.AlterField(
            model_name="idcounter",
            name="sequential",
            field=models.IntegerField(
                default=0, help_text="Sequential number (0001-9999)"
            ),
        ),
        migrations.AlterField(
            model_name="idcounter",
            name="year",
            field=models.IntegerField(help_text="The year for this ID sequence"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["course_section"], name="core_activi_course__6db802_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["deadline"], name="core_activi_deadlin_0a1537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(
                fields=["course"], name="core_course_course__c9850a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(
                fields=["teacher"], name="core_course_teacher_6f1cd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursesection",
            index=models.Index(
                fields=["course", "teacher"], name="core_course_course__11e317_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["activity"], name="core_submis_activit_35105e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student"], name="core_submis_student_323fea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["activity", "student"], name="core_submis_activit_63bf10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="core_user_email_38052c_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="core_user_role_73872d_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["status"], name="core_user_status_6589e6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["student_id"], name="core_user_student_1b1f27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["employee_id"], name="core_user_employe_506d81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "status"], name="core_user_role_11c99b_idx"
            ),
        ),
    ]
