# Generated by Django 5.2.12 on 2026-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_add_audit_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="allow_late_submissions",
            field=models.BooleanField(default=True),
        ),
    ]
