# Generated by Django 5.2.12 on 2026-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_activity_allow_late_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="alternate_answers",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="case_sensitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="correct_answer",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="word_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("multi_select", "Multiple Select"),
                    ("true_false", "True/False"),
                    ("identification", "Identification"),
                    ("essay", "Essay"),
                ],
                max_length=30,
            ),
        ),
    ]
