# Generated by Django 5.2.12 on 2026-04-07 23:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_quiz_question_new_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "school_year",
                    models.CharField(
                        help_text="Academic year e.g., '2024-2025'", max_length=20
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("quarter", "Quarter"), ("semester", "Semester")],
                        help_text="Quarter for grades 7-10, Semester for grades 11-12",
                        max_length=10,
                    ),
                ),
                (
                    "period_number",
                    models.PositiveSmallIntegerField(
                        help_text="1-4 for quarters, 1-2 for semesters"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of this grading period"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="End date of this grading period"),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the current active grading period",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Grading Period",
                "verbose_name_plural": "Grading Periods",
                "ordering": ["school_year", "period_number"],
                "indexes": [
                    models.Index(
                        fields=["school_year"], name="core_gradin_school__2d9b30_idx"
                    ),
                    models.Index(
                        fields=["is_current"], name="core_gradin_is_curr_be98de_idx"
                    ),
                ],
                "unique_together": {("school_year", "period_type", "period_number")},
            },
        ),
        migrations.CreateModel(
            name="GradeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "computed_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-computed from activities/quizzes",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "override_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Teacher-entered manual override",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this grade is visible to students",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="core.enrollment",
                        verbose_name="Enrollment",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_entries",
                        to="core.gradingperiod",
                        verbose_name="Grading Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Entry",
                "verbose_name_plural": "Grade Entries",
                "ordering": ["enrollment", "grading_period__period_number"],
                "indexes": [
                    models.Index(
                        fields=["enrollment"], name="core_gradee_enrollm_7685df_idx"
                    ),
                    models.Index(
                        fields=["grading_period"], name="core_gradee_grading_3f4e07_idx"
                    ),
                    models.Index(
                        fields=["is_published"], name="core_gradee_is_publ_b1a645_idx"
                    ),
                ],
                "unique_together": {("enrollment", "grading_period")},
            },
        ),
        migrations.CreateModel(
            name="AssignmentWeight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("activity", "Activity"),
                            ("quiz", "Quiz"),
                            ("exam", "Exam"),
                        ],
                        help_text="Type of assignment: activity, quiz, or exam",
                        max_length=10,
                    ),
                ),
                (
                    "weight_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight as percentage (e.g., 30.00 for 30%)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_weights",
                        to="core.coursesection",
                        verbose_name="Course Section",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignment_weights",
                        to="core.gradingperiod",
                        verbose_name="Grading Period",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment Weight",
                "verbose_name_plural": "Assignment Weights",
                "ordering": ["course_section", "grading_period", "category"],
                "unique_together": {("course_section", "grading_period", "category")},
            },
        ),
    ]
