# Generated by Django 5.2.12 on 2026-04-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_gradingperiod_gradeentry_assignmentweight"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradingperiod",
            options={
                "ordering": ["school_year", "semester_group", "period_number"],
                "verbose_name": "Grading Period",
                "verbose_name_plural": "Grading Periods",
            },
        ),
        migrations.AlterUniqueTogether(
            name="gradingperiod",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="gradingperiod",
            name="semester_group",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="For Grades 11-12: 1 for Q1+Q2 (1st Sem), 2 for Q3+Q4 (2nd Sem). Null for Grades 7-10.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gradingperiod",
            name="period_number",
            field=models.PositiveSmallIntegerField(help_text="1-4 for Q1, Q2, Q3, Q4"),
        ),
        migrations.AlterField(
            model_name="gradingperiod",
            name="period_type",
            field=models.CharField(
                choices=[("quarter", "Quarter")],
                default="quarter",
                help_text="Always 'quarter' - semesters are computed from quarter groups",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradingperiod",
            unique_together={("school_year", "semester_group", "period_number")},
        ),
        migrations.AddIndex(
            model_name="gradingperiod",
            index=models.Index(
                fields=["semester_group"], name="core_gradin_semeste_9f9c6c_idx"
            ),
        ),
    ]
