# Generated by Django 5.2.12 on 2026-04-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_add_semester_group_to_grading_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_final_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the final grade is visible to students",
            ),
        ),
    ]
