# Generated by Django 5.2.12 on 2026-04-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_add_is_final_published_to_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("languages_ap_esp", "Languages, AP, ESP"),
                    ("science_math", "Science and Math"),
                    ("mapeh_epp_tle", "MAPEH, EPP, TLE"),
                    ("shs_core", "SHS Core Subject"),
                    ("shs_applied", "SHS Applied Subject"),
                    ("shs_specialized", "SHS Specialized Subject"),
                    ("shs_tvl", "SHS TVL Track"),
                ],
                help_text="Subject classification for DepEd grade weight defaults",
                max_length=30,
                null=True,
            ),
        ),
    ]
