# Generated by Django 5.2.12 on 2026-04-10 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_course_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("languages_ap_esp", "Languages, AP, ESP"),
                    ("science_math", "Science and Math"),
                    ("mapeh_epp_tle", "MAPEH, EPP, TLE"),
                    ("shs_core", "SHS Core Subject"),
                    ("shs_applied", "SHS Applied Subject"),
                    ("shs_specialized", "SHS Specialized Subject"),
                    ("shs_tvl", "SHS TVL Track"),
                ],
                help_text="Subject classification for DepEd grade weight defaults",
                max_length=30,
                null=True,
                verbose_name="Subject Category",
            ),
        ),
        migrations.CreateModel(
            name="GradeWeightConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "written_works",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Weight for Written Works component (quizzes + written activities + monthly exams)",
                        verbose_name="Written Works Weight (%)",
                    ),
                ),
                (
                    "performance_tasks",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Weight for Performance Tasks component (performance activities)",
                        verbose_name="Performance Tasks Weight (%)",
                    ),
                ),
                (
                    "quarterly_assessment",
                    models.PositiveIntegerField(
                        default=25,
                        help_text="Weight for Quarterly Assessment component (quarterly exams)",
                        verbose_name="Quarterly Assessment Weight (%)",
                    ),
                ),
                (
                    "is_customized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the teacher has customized the weights from DepEd defaults",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_weight_config",
                        to="core.coursesection",
                        verbose_name="Course Section",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grade_weight_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Weight Configuration",
                "verbose_name_plural": "Grade Weight Configurations",
            },
        ),
    ]
