# Generated by Django 5.2.12 on 2026-04-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_course_category_gradeweightconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="component_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("written_works", "Written Works"),
                    ("performance_task", "Performance Task"),
                    ("quarterly_assessment", "Quarterly Assessment"),
                ],
                help_text="DepEd grade component: Written Works, Performance Task, or Quarterly Assessment",
                max_length=25,
                null=True,
                verbose_name="Component Type",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="exam_type",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly Exam"), ("quarterly", "Quarterly Exam")],
                help_text="Type of exam: Monthly (counts as Written Works) or Quarterly (counts as Quarterly Assessment)",
                max_length=10,
                null=True,
                verbose_name="Exam Type",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_exam",
            field=models.BooleanField(
                default=False,
                help_text="Whether this activity is an exam (Monthly or Quarterly)",
                verbose_name="Is Exam",
            ),
        ),
    ]
