# Generated by Django 5.2.12 on 2026-04-10 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_activity_component_type_activity_exam_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradeentry",
            name="adviser_overridden",
            field=models.BooleanField(
                default=False, help_text="Whether an adviser has overridden this grade"
            ),
        ),
        migrations.CreateModel(
            name="AdviserOverrideLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("new_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adviser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adviser_overrides",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Adviser",
                    ),
                ),
                (
                    "grade_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="override_logs",
                        to="core.gradeentry",
                        verbose_name="Grade Entry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adviser Override Log",
                "verbose_name_plural": "Adviser Override Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GradeSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("taken_back_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course_section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_submissions",
                        to="core.coursesection",
                        verbose_name="Course Section",
                    ),
                ),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_submissions",
                        to="core.gradingperiod",
                        verbose_name="Grading Period",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_grades",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grade Submission",
                "verbose_name_plural": "Grade Submissions",
                "ordering": ["-created_at"],
                "unique_together": {("course_section", "grading_period")},
            },
        ),
        migrations.CreateModel(
            name="SectionReportCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grading_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="core.gradingperiod",
                        verbose_name="Grading Period",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_report_cards",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Published By",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_cards",
                        to="core.section",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Report Card",
                "verbose_name_plural": "Section Report Cards",
                "ordering": ["-created_at"],
                "unique_together": {("section", "grading_period")},
            },
        ),
    ]
