# Generated by Django 5.2.12 on 2026-04-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_thread_student(apps, schema_editor):
    ActivityComment = apps.get_model("core", "ActivityComment")

    comments = ActivityComment.objects.select_related(
        "submission__student",
        "author",
        "parent__submission__student",
        "parent__author",
        "parent__thread_student",
    )

    for comment in comments.iterator():
        thread_student_id = None

        if comment.submission_id:
            thread_student_id = comment.submission.student_id
        elif comment.parent_id:
            parent = comment.parent
            if parent.thread_student_id:
                thread_student_id = parent.thread_student_id
            elif parent.submission_id:
                thread_student_id = parent.submission.student_id
            elif parent.author and parent.author.role == "student":
                thread_student_id = parent.author_id

        if not thread_student_id and comment.author and comment.author.role == "student":
            thread_student_id = comment.author_id

        if thread_student_id and comment.thread_student_id != thread_student_id:
            ActivityComment.objects.filter(id=comment.id).update(thread_student_id=thread_student_id)


def reverse_backfill_thread_student(apps, schema_editor):
    # Keep populated thread ownership data during reverse migrations.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_backfill_grade_submissions_and_report_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycomment",
            name="thread_student",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "student"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_comment_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_thread_student, reverse_backfill_thread_student),
    ]
