# Generated by Django 5.2.12 on 2026-04-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_activitycomment_thread_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefile",
            name="file_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="coursefile",
            name="preview_file_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
