# Generated by Django 5.2.12 on 2026-04-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_coursefile_file_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="support_file_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="cover_image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
