from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    ActivityCommentViewSet,
    ActivityCommentsByActivityView,
    ActivityReminderViewSet,
    AdviserOverrideView,
    AttendanceOverviewView,
    AttendanceRecordBulkUpdateView,
    AttendanceSessionCreateView,
    AttendanceSessionDeleteView,
    ActivityMySubmissionView,
    ActivitySubmissionGradeView,
    ActivitySubmissionsForTeacherView,
    ActivitySubmitView,
    ActivityViewSet,
    AnnouncementViewSet,
    AssignmentGroupViewSet,
    AuthLoginView,
    AuthLogoutView,
    AvatarUploadView,
    CalendarEventViewSet,
    ChangePasswordView,
    CourseFileViewSet,
    CourseSectionContentView,
    CourseSectionDetailView,
    CourseSectionGradebookView,
    CourseSectionGradesView,
    CourseSectionGradesExportCSVView,
    DashboardStatsView,
    EnrollmentGradeOverrideView,
    ForgotPasswordRequestView,
    GradeSubmissionSubmitView,
    GradeSubmissionTakeBackView,
    GradeWeightConfigView,
    GradingPeriodListView,
    ReportCardPublishView,
    ReportCardUnpublishView,
    StudentGradesView,
    StudentReportCardView,
    AdvisoryGradesView,
    SubjectGradesView,
    GradeEntryCreateView,
    GradeEntryUpdateView,
    GradeEntryPublishView,
    BulkPublishGradesView,
    BulkPublishFinalGradesView,
    ComputeFinalGradeView,
    MeView,
    NotificationViewSet,
    PasswordResetRequestViewSet,
    ProfileViewSet,
    PushTokenViewSet,
    QuizAnswerGradeView,
    QuizGradingListView,
    QuizMyLatestAttemptView,
    QuizQuestionDetailView,
    QuizQuestionsBulkView,
    QuizQuestionsView,
    QuizQuickCreateView,
    QuizSaveProgressView,
    QuizSubmitAttemptView,
    QuizTakeView,
    QuizViewSet,
    StudentCoursesView,
    WeeklyModuleViewSet,
    TeacherCoursesView,
    TodoItemViewSet,
)

router = DefaultRouter()
router.register(r"profiles", ProfileViewSet, basename="profiles")
router.register(r"todos", TodoItemViewSet, basename="todos")
router.register(r"calendar-events", CalendarEventViewSet, basename="calendar-events")
router.register(r"notifications", NotificationViewSet, basename="notifications")
router.register(r"course-modules", WeeklyModuleViewSet, basename="course-modules")
router.register(r"assignment-groups", AssignmentGroupViewSet, basename="assignment-groups")
router.register(r"activities", ActivityViewSet, basename="activities")
router.register(r"course-files", CourseFileViewSet, basename="course-files")
router.register(r"announcements", AnnouncementViewSet, basename="announcements")
router.register(r"quizzes", QuizViewSet, basename="quizzes")
router.register(r"password-reset-requests", PasswordResetRequestViewSet, basename="password-reset-requests")
router.register(r"push-tokens", PushTokenViewSet, basename="push-tokens")
router.register(r"reminders", ActivityReminderViewSet, basename="reminders")
router.register(r"activity-comments", ActivityCommentViewSet, basename="activity-comments")

urlpatterns = [
    path("auth/login/", AuthLoginView.as_view(), name="auth-login"),
    path("auth/logout/", AuthLogoutView.as_view(), name="auth-logout"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/refresh/", TokenRefreshView.as_view(), name="token-refresh"),
    path("auth/change-password/", ChangePasswordView.as_view(), name="auth-change-password"),
    path("auth/forgot-password/", ForgotPasswordRequestView.as_view(), name="auth-forgot-password"),
    path("profiles/me/avatar/", AvatarUploadView.as_view(), name="profile-avatar-upload"),
    path("dashboard/stats/", DashboardStatsView.as_view(), name="dashboard-stats"),
    path("courses/student/", StudentCoursesView.as_view(), name="student-courses"),
    path("courses/teacher/", TeacherCoursesView.as_view(), name="teacher-courses"),
    path("course-sections/<uuid:pk>/", CourseSectionDetailView.as_view(), name="course-section-detail"),
    path("course-sections/<uuid:pk>/content/", CourseSectionContentView.as_view(), name="course-section-content"),
    path("course-sections/<uuid:pk>/grades/export/", CourseSectionGradesExportCSVView.as_view(), name="course-section-grades-export"),
    path("course-sections/<uuid:pk>/gradebook/", CourseSectionGradebookView.as_view(), name="course-section-gradebook"),
    path("course-sections/<uuid:pk>/grades/", CourseSectionGradesView.as_view(), name="course-section-grades"),
    path("course-sections/<uuid:pk>/grade-weights/", GradeWeightConfigView.as_view(), name="grade-weight-config"),
    path(
        "course/<uuid:course_id>/section/<uuid:section_id>/grades/export/",
        CourseSectionGradesExportCSVView.as_view(),
        name="course-section-grades-export-alt",
    ),
    path("enrollments/<uuid:pk>/grade-override/", EnrollmentGradeOverrideView.as_view(), name="enrollment-grade-override"),
    path("course-sections/<uuid:pk>/attendance/", AttendanceOverviewView.as_view(), name="attendance-overview"),
    path("course-sections/<uuid:pk>/attendance/sessions/", AttendanceSessionCreateView.as_view(), name="attendance-session-create"),
    path("attendance/sessions/<uuid:pk>/", AttendanceSessionDeleteView.as_view(), name="attendance-session-delete"),
    path("attendance/sessions/<uuid:pk>/records/", AttendanceRecordBulkUpdateView.as_view(), name="attendance-records-update"),
    path("activities/<uuid:pk>/submit/", ActivitySubmitView.as_view(), name="activity-submit"),
    path("activities/<uuid:pk>/my-submission/", ActivityMySubmissionView.as_view(), name="activity-my-submission"),
    path("activities/<uuid:pk>/submissions/", ActivitySubmissionsForTeacherView.as_view(), name="activity-submissions"),
    path("activity-submissions/<uuid:pk>/grade/", ActivitySubmissionGradeView.as_view(), name="activity-submission-grade"),
    path("quizzes/<uuid:pk>/take/", QuizTakeView.as_view(), name="quiz-take"),
    path("quizzes/<uuid:pk>/submit-attempt/", QuizSubmitAttemptView.as_view(), name="quiz-submit-attempt"),
    path("quizzes/<uuid:pk>/save-progress/", QuizSaveProgressView.as_view(), name="quiz-save-progress"),
    path("quizzes/<uuid:pk>/my-latest-attempt/", QuizMyLatestAttemptView.as_view(), name="quiz-my-latest-attempt"),
    path("quizzes/<uuid:pk>/grading/", QuizGradingListView.as_view(), name="quiz-grading-list"),
    path("quiz-answers/<uuid:pk>/grade/", QuizAnswerGradeView.as_view(), name="quiz-answer-grade"),
    path("quizzes/quick-create/", QuizQuickCreateView.as_view(), name="quiz-quick-create"),
    path("quizzes/<uuid:pk>/questions/bulk/", QuizQuestionsBulkView.as_view(), name="quiz-questions-bulk"),
    path("quizzes/<uuid:pk>/questions/", QuizQuestionsView.as_view(), name="quiz-questions"),
    path("quiz-questions/<uuid:pk>/", QuizQuestionDetailView.as_view(), name="quiz-question-detail"),
    path("activities/<uuid:pk>/comments/", ActivityCommentsByActivityView.as_view(), name="activity-comments"),
    path("grading-periods/", GradingPeriodListView.as_view(), name="grading-periods"),
    path("course-sections/<uuid:pk>/grades/student/", StudentGradesView.as_view(), name="student-grades"),
    path("sections/<uuid:section_id>/grades/advisory/", AdvisoryGradesView.as_view(), name="advisory-grades"),
    path("course-sections/<uuid:pk>/grades/subject/", SubjectGradesView.as_view(), name="subject-grades"),
    path("grade-entries/", GradeEntryCreateView.as_view(), name="grade-entry-create"),
    path("grade-entries/<uuid:pk>/", GradeEntryUpdateView.as_view(), name="grade-entry-update"),
    path("grade-entries/<uuid:pk>/publish/", GradeEntryPublishView.as_view(), name="grade-entry-publish"),
    path("course-sections/<uuid:pk>/grades/bulk-publish/", BulkPublishGradesView.as_view(), name="grades-bulk-publish"),
    path("course-sections/<uuid:pk>/grades/bulk-publish-final/", BulkPublishFinalGradesView.as_view(), name="grades-bulk-publish-final"),
    path("enrollments/<uuid:pk>/compute-final-grade/", ComputeFinalGradeView.as_view(), name="enrollment-compute-final-grade"),
    path("course-sections/<uuid:pk>/grades/submit/", GradeSubmissionSubmitView.as_view(), name="grade-submission-submit"),
    path("course-sections/<uuid:pk>/grades/take-back/", GradeSubmissionTakeBackView.as_view(), name="grade-submission-take-back"),
    path("advisory/<uuid:section_id>/report-card/publish/", ReportCardPublishView.as_view(), name="report-card-publish"),
    path("advisory/<uuid:section_id>/report-card/unpublish/", ReportCardUnpublishView.as_view(), name="report-card-unpublish"),
    path("grade-entries/<uuid:pk>/adviser-override/", AdviserOverrideView.as_view(), name="adviser-override"),
    path("students/me/report-card/", StudentReportCardView.as_view(), name="student-report-card"),
    path("", include(router.urls)),
]
